### ISSUE TITLE
windows users encounter 260 characters path limit restriction when using lib

### ISSUE THREAD

**Issue by ivstas** [victorporof/rsx#1]
Hi.
I created an issue just for case if anybody of windows users that would try `rsx` macro would tell you that their build is failing.

Cargo puts git dependencies under `.cargo/git` subfolder in users directory. When dealing with dependencies containing many nested folders, you can encounter situation like this:
```
[2/-4] failed to stat 'C:/Users/ivstas/.cargo/git/checkouts/servo-css-parser-6b649679bab5995b/0d528c7/servo/tests/wpt/mozilla/meta/mozilla/referrer-policy/origin-when-cross-origin/attr-referrer/same-origin/http-https/iframe-tag/same-origin-downgrade.keep-origin-redirect.http.html.ini': The filename or extension is too long.
````

Actually, file path is 261 characters, exceeding windows standard limit by 1 character.
Unfortunatelly, using windows feature that extends this limit didn't affect `cargo`, so I filed an issue in cargo repo. This issue is just for you to be aware of the problem.

**Comment by infogulch** [comment]
References:

Cargo may hit 260 characters path limit on windows when installing dependencies \#4745:

`https://github.com/rust-lang/cargo/issues/4745`

Support core.longpaths on Windows \#3053:

`https://github.com/libgit2/libgit2/issues/3053`

> #### `@ethomson` commented **`May 5, 2021`**:
> `@ianhattendorf` has added longpath support, and it is now available in main. 🎉

So... fixed?
